HumanCapitalManagementSystem/HCMS.Web/Controllers/AdvertController.cs
using AutoMapper;
using HCMS.Web.ViewModels.Advert;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;
using static HCMS.Common.RoleConstants;
using static HCMS.Common.NotificationMessagesConstants;
using HCMS.Services.ServiceModels.Advert;
using HCMS.Web.ViewModels.BaseViewModel;
using HCMS.Services.ServiceModels.BaseClasses;

namespace HCMS.Web.Controllers
{
    public class AdvertController : Controller
    {

        private readonly HttpClient httpClient;
        private readonly IMapper mapper;

        public AdvertController(IHttpClientFactory httpClientFactory, IMapper mapper)
        {
            httpClient = httpClientFactory.CreateClient("WebApi");
            this.mapper = mapper;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All(AdvertPageQueryModel queryModel)
        {
            if (queryModel == null)
            {
                queryModel = new AdvertPageQueryModel();
            }

            AdvertQueryDto advertQueryDto = mapper.Map<AdvertQueryDto>(queryModel);

            string url = $"api/advert/all";
            string json = JsonConvert.SerializeObject(advertQueryDto, Formatting.Indented);
            HttpContent content = new StringContent(json, Encoding.UTF8, "application/json");

            HttpResponseMessage response = await httpClient.PostAsync(url, content);

            if (response.IsSuccessStatusCode)
            {
                string jsonContent = await response.Content.ReadAsStringAsync();
                AdvertQueryDtoResult responseQueryDto = JsonConvert.DeserializeObject<AdvertQueryDtoResult>(jsonContent, JsonSerializerSettingsProvider.GetCustomSettings())!;
                AdvertResultQueryModel advertQueryModel = mapper.Map<AdvertResultQueryModel>(responseQueryDto);
                return View(advertQueryModel);
            }
            TempData[ErrorMessage] = "No job offers were found!";
            return View("Home", "Home");
        }


        [HttpGet]
        public IActionResult Details()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = $"{AGENT},{ADMIN}")]
        public IActionResult Add()
        {
            if(User.Claims.Any(c => c.Type == "EmployeeCompanyId"))
            {
                return View();
            }
            TempData[ErrorMessage] = "You must be first employed into a company as agent to be able to add job offers!";
            return RedirectToAction("Home", "Home");
        }

        [HttpPost]
        [Authorize(Roles = $"{AGENT},{ADMIN}")]
        public async Task<IActionResult> Add(AdvertFormModel model)
        {
            //validate input
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            AdvertAddDto advertDto = mapper.Map<AdvertAddDto>(model);

            string jsonContent = JsonConvert.SerializeObject(advertDto, Formatting.Indented, JsonSerializerSettingsProvider.GetCustomSettings());
            HttpContent content = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            string apiUrl = "/api/advert/add";

            //set JWT
            string tokenString = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

            HttpResponseMessage response = await httpClient.PostAsync(apiUrl, content);

            //if advert added successfully
            if (response.IsSuccessStatusCode)
            {
                TempData[SuccessMessage] = "Advert was successfully added!";
                return RedirectToAction("Home", "Home");
            }
            else
            {
                TempData[ErrorMessage] = response.Content.ToString();
                return View(model);
            }
        }
    }
}

HumanCapitalManagementSystem/HCMS.Web/Controllers/EmployeeController.cs
using AutoMapper;
using HCMS.Common;
using HCMS.Services.ServiceModels.BaseClasses;
using HCMS.Services.ServiceModels.Employee;
using HCMS.Web.ViewModels.BaseViewModel;
using HCMS.Web.ViewModels.Employee;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using static HCMS.Common.NotificationMessagesConstants;

namespace HCMS.Web.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly HttpClient httpClient;
        private readonly IMapper mapper;

        public EmployeeController(IHttpClientFactory httpClientFactory, IMapper mapper)
        {
            httpClient = httpClientFactory.CreateClient("WebApi");
            this.mapper = mapper;
        }

        [HttpGet]
        [Authorize(Roles = $"{RoleConstants.AGENT},{RoleConstants.ADMIN}")]
        public async Task<IActionResult> All(QueryDto model)
        {
            if (model == null)
            {
                model = new QueryDto();
            }

            string url = "api/employee/page";
            string json = JsonConvert.SerializeObject(model);
            HttpContent content = new StringContent(json, Encoding.UTF8, "application/json");

            //set JWT
            string tokenString = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

            HttpResponseMessage response = await httpClient.PostAsync(url, content);

            if (response.IsSuccessStatusCode)
            {
                string jsonContent = await response.Content.ReadAsStringAsync();
                QueryDtoResult<EmployeeDto> responseQueryDto = JsonConvert.DeserializeObject<QueryDtoResult<EmployeeDto>>(jsonContent, JsonSerializerSettingsProvider.GetCustomSettings())!;
                ResultQueryModel<EmployeeViewModel> employeeQueryModel = mapper.Map<ResultQueryModel<EmployeeViewModel>>(responseQueryDto);
                return View(employeeQueryModel);
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(string? redirect)
        {
            //check if it is redirect
            if (redirect != null)
            {
                TempData[WarningMessage] = redirect;
                return View(new EmployeeFormModel());
            }

            //get currently logged user ID
            Claim userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserId")!;
            string userId = userIdClaim.Value;

            //set the userIdGuid as query param
            string apiUrl = $"/api/employee/GetEmployeeDtoByUserId?userId={userId}";

            //set the JWT to the httpClient
            string JWT = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", JWT);

            // Make get request
            HttpResponseMessage response = await httpClient.GetAsync(apiUrl);


            if (response.IsSuccessStatusCode)
            {


                // Read the content as a JSON string
                string jsonContent = await response.Content.ReadAsStringAsync();

                // Deserialize the JSON into an EmployeeDto object

                //deserializing (if not working check the request from the other side) the JsonSerializerSettingsProvider is custom made in common
                EmployeeDto? employeeDto = JsonConvert.DeserializeObject<EmployeeDto>(jsonContent, JsonSerializerSettingsProvider.GetCustomSettings());

                //check if employee is not empty and attach it as a view model
                if (employeeDto != null)
                {
                    EmployeeFormModel model = mapper.Map<EmployeeFormModel>(employeeDto);
                    return View(model);
                }
            }
            return View(new EmployeeFormModel());
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(EmployeeFormModel model)
        {
            //validate input
            if (!ModelState.IsValid)
            {
                TempData[ErrorMessage] = "Please fulfill the requirements of the input fields!";
                return View(model);
            }
            //Validations completed
            Claim userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserId")!;

            EmployeeDto employeeDto = mapper.Map<EmployeeDto>(model);
            employeeDto.UserId = Guid.Parse(userIdClaim.Value);

            using (var form = new MultipartFormDataContent())
            {
                // Add the file content
                if (model.Photo != null)
                {
                    // Use a MemoryStream without disposing it here
                    var stream = new MemoryStream();
                    await model.Photo.CopyToAsync(stream);
                    stream.Position = 0;
                    form.Add(new StreamContent(stream), "file", model.Photo.FileName);
                }

                employeeDto.Photo = null;
                string jsonContent = JsonConvert.SerializeObject(employeeDto, JsonSerializerSettingsProvider.GetCustomSettings());
                form.Add(new StringContent(jsonContent, Encoding.UTF8, "application/json"), "employeeDto");

                string apiUrl = "/api/employee/UpdateEmployee";

                // Set JWT
                string tokenString = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
                this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

                HttpResponseMessage response = await httpClient.PostAsync(apiUrl, form);

                //if employee information successfully updated
                if (response.IsSuccessStatusCode)
                {
                    //if the principal has no employeeId claim -> add employee information for first time
                    if (!HttpContext.User.Claims.Any(c => c.Type == "EmployeeId"))
                    {
                        string userId = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserId")!.Value;

                        //JWT is already set
                        //set the employeeId to the claims of the user
                        string employeeApiUrl = $"/api/employee/EmployeeIdByUserId?UserId={userId}";
                        HttpResponseMessage employeeIdResponse = await httpClient.GetAsync(employeeApiUrl);
                        if (employeeIdResponse.IsSuccessStatusCode)
                        {
                            var userClaims = new List<Claim>(HttpContext.User.Claims);

                            // Add / update claims
                            string employeeId = await employeeIdResponse.Content.ReadAsStringAsync();
                            Claim employeeIdClaim = new Claim("EmployeeId", employeeId);
                            userClaims.RemoveAll(c => c.Type == "EmployeeId");
                            userClaims.Add(employeeIdClaim);

                            ClaimsIdentity updatedIdentity = new ClaimsIdentity(userClaims, HttpContext.User.Identity!.AuthenticationType, ClaimTypes.Name, ClaimTypes.Role);

                            ClaimsPrincipal updatedPrincipal = new ClaimsPrincipal(updatedIdentity);

                            await HttpContext.SignInAsync(updatedPrincipal);
                        }
                    }

                    TempData[SuccessMessage] = "You have successfully edited your personal information!";
                    return RedirectToAction("Home", "Home");
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                {
                    // Read the response content as a string
                    string responseContent = await response.Content.ReadAsStringAsync();
                    ModelState.AddModelError("GeneralError", responseContent);
                    return View(model);
                }
                else
                {
                    ModelState.AddModelError("GeneralError", "Unexpected error occurred!");
                    TempData[ErrorMessage] = "Unexpected error occurred!";
                    return View(model);
                }
            }
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Dismiss(string id)
        {
            //set the userIdGuid as query param
            string apiUrl = $"/api/employee/Dismiss?id={id}";

            //set the JWT to the httpClient
            string JWT = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", JWT);

            // Make get request
            HttpResponseMessage response = await httpClient.GetAsync(apiUrl);


            if (response.IsSuccessStatusCode)
            {
                TempData[SuccessMessage] = "You have successfully left the company!";
                return RedirectToAction("Home", "Home");
            }
            else
            {
                TempData[ErrorMessage] = await response.Content.ReadAsStringAsync();
                return RedirectToAction("Company", "Select");
            }
        }


    }
}

HumanCapitalManagementSystem/HCMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>HCMS @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HCMS.Web.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js" integrity="sha512-lbwH47l/tPXJYG9AcFNoJaTMhGvYWhVM9YI43CT+uteTRRaiLCui8snIgyAN8XWgNjNhCqlAUdzZptso6OCoFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha512-oe8OpYjBaDWPt2VmSFR+qYOdnTjeV9QPLJUeqZyprDEQvQLJ9C5PCFclxwNuvb/GQgQngdCXzKSFltuHD3eCxA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        @*toastr*@
        <partial name="_NotificationsPartial" />

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand text-white technical-font" asp-area="" asp-controller="Home" asp-action="Index">HCMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item technical-font">
                            <partial name="_LeftDropdownPartial" />
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_RightDropdownPartial" />
        </nav>
    </header>

    <main role="main" class="my-5 mx-auto pb-3">
        @RenderBody()
    </main>
    <footer class="footer text-white">
        <div class="container">
            2023 - Human Capital Management System - Yordan Milanov Project
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HumanCapitalManagementSystem/HCMS.Web/Views/Shared/_LeftDropdownPartial.cshtml
@using HCMS.Common;
@using static HCMS.Common.RoleConstants;
<ul class="navbar-nav mx-3">
    <li class="nav-item dropdown">
        <button type="button" class="btn btn-secondary dropdown-toggle dropdown-item" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">Jobs</button>
        <ul class="dropdown-menu dropdown-menu-lg-end custom-dropdown-menu my-2">
            <li><a class="dropdown-item" asp-controller="Advert" asp-action="All">All jobs</a></li>
            @if (User.Identity!.IsAuthenticated)
            {
                @if(User.Claims.Where(c => c.Type == "CompanyId").FirstOrDefault() != null)
                {
                    <li><a asp-controller="Advert" asp-action="All" asp-route-id="@User.Claims.Where(c => c.Type == "CompanyId").FirstOrDefault()!.Value" class="dropdown-item">My company jobs</a></li>
                }
                @if (User.IsInRole(AGENT) || User.IsInRole(ADMIN))
                {
                    <li><a asp-controller="Advert" asp-action="Add" class="dropdown-item">Add job</a></li>
                }
            }
        </ul>
    </li>
</ul>

HumanCapitalManagementSystem/HCMS.Web/Views/Shared/_Modal.cshtml
@model string;

<div id="confirmationModal" class="modal">
    
    <div class="modal-dialog">
        <div class="modal-content">
           
            <div class="modal-header">
                <h5 class="modal-title">Confirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">@Model</div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button id="confirmDelete" class="btn btn-danger">Delete</button>
            </div>

        </div>
    </div>

</div>

HumanCapitalManagementSystem/HCMS.Web/Views/Shared/_NotificationsPartial.cshtml
@using static HCMS.Common.NotificationMessagesConstants

@if (TempData.ContainsKey(ErrorMessage))
{
    <script>toastr.error(`@TempData[ErrorMessage]`);</script>
}
@if (TempData.ContainsKey(WarningMessage))
{
    <script>toastr.warning(`@TempData[WarningMessage]`);</script>
}
@if (TempData.ContainsKey(InformationMessage))
{
    <script>toastr.info(`@TempData[InformationMessage]`);</script>
}
@if (TempData.ContainsKey(SuccessMessage))
{
    <script>toastr.success(`@TempData[SuccessMessage]`);</script>
}

HumanCapitalManagementSystem/HCMS.Web/Views/Shared/_RightDropdownPartial.cshtml
@using HCMS.Common;
<ul class="navbar-nav mx-3">
    @if (User.Identity!.IsAuthenticated)
    {
        <li class="nav-item dropdown">
            <button type="button" class="btn btn-secondary dropdown-toggle dropdown-item" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                    @User.Claims.FirstOrDefault(c => c.Type == "Username")!.Value
                </button>
            <ul class="dropdown-menu dropdown-menu-lg-end custom-dropdown-menu my-2">
                <li><a class="dropdown-item" asp-controller="User" asp-action="Profile" asp-route-id="@User.Claims.FirstOrDefault(c => c.Type == "UserId")!.Value">Profile</a></li>
                @if (User.IsInRole(RoleConstants.ADMIN))
                {
                    <li><a asp-controller="Company" asp-action="Select" class="dropdown-item">Select workplace</a></li>
                }
                @if (User.IsInRole(RoleConstants.AGENT) || User.IsInRole(RoleConstants.ADMIN))
                {
                    <li><a asp-controller="Employee" asp-action="Edit" class="dropdown-item">Edit Personal Information</a></li>
                    <li><a asp-controller="Education" asp-action="Edit" class="dropdown-item">Add Education</a></li>
                }
                <li><a class="dropdown-item" asp-controller="Education" asp-action="All" asp-route-id="@User.Claims.FirstOrDefault(c => c.Type == "EmployeeId")?.Value">My Educations</a></li>
                @if (User.IsInRole(RoleConstants.AGENT) || User.IsInRole(RoleConstants.ADMIN))
                {
                    <li><a asp-controller="WorkRecord" asp-action="Add" class="dropdown-item">Add Work Record</a></li>

                }
                <li><a class="dropdown-item" asp-controller="WorkRecord" asp-action="AllPersonal" asp-route-id="@User.Claims.FirstOrDefault(c => c.Type == "EmployeeId")?.Value">My Work Records</a></li>
                <li><a class="dropdown-item" href="/User/Logout">Logout</a></li>
            </ul>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-white" href="/User/Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-white" href="/User/Login">Login</a>
        </li>
    }
</ul>