HumanCapitalManagementSystem/HCMS.Web/Controllers/ApplicationController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static HCMS.Common.RoleConstants;
using static HCMS.Common.NotificationMessagesConstants;
using HCMS.Web.ViewModels.Application;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Text;
using HCMS.Services.ServiceModels.Application;
using HCMS.Services.ServiceModels.Advert;
using HCMS.Web.ViewModels.Advert;
using HCMS.Services.ServiceModels.BaseClasses;
using HCMS.Services.ServiceModels.Employee;
using HCMS.Web.ViewModels.BaseViewModel;
using HCMS.Web.ViewModels.Employee;
using System.Reflection;

namespace HCMS.Web.Controllers
{
    public class ApplicationController : Controller
    {

        private readonly HttpClient httpClient;
        private readonly IMapper mapper;

        public ApplicationController(IHttpClientFactory httpClientFactory, IMapper mapper)
        {
            httpClient = httpClientFactory.CreateClient("WebApi");
            this.mapper = mapper;
        }

        [HttpGet]
        [Authorize(Roles = $"{AGENT},{ADMIN}")]
        public IActionResult All()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public IActionResult Apply(string advertId, string employeeId, string job)
        {
            if (!HttpContext.User.HasClaim(c => c.Type == "EmployeeId"))
            {
                TempData[ErrorMessage] = "First you need to add your employee information to be able to apply for job!";
                return View("Advert", "All");
            }

            ApplicationFormModel model = new ApplicationFormModel();
            model.AdvertId = Guid.Parse(advertId);
            model.FromEmployeeId = Guid.Parse(employeeId);
            ViewData["Job"] = job;
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Apply(ApplicationFormModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData[ErrorMessage] = "Please fulfill the requirements of the input fields!";
                return View(model);
            }
 

            ApplicationDto applicationDto = mapper.Map<ApplicationDto>(model);
            string jsonContent = JsonConvert.SerializeObject(applicationDto, JsonSerializerSettingsProvider.GetCustomSettings());
            HttpContent content = new StringContent(jsonContent, Encoding.UTF8, "application/json");


            string url = $"api/application/apply";

            //set JWT
            string tokenString = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

            HttpResponseMessage response = await httpClient.PostAsync(url, content);

            string messageResponse = await response.Content.ReadAsStringAsync();
            if (response.IsSuccessStatusCode)
            {
                TempData[SuccessMessage] = messageResponse.Substring(1,messageResponse.Length - 2);
            } 
            else
            {
                TempData[ErrorMessage] = messageResponse.Substring(1, messageResponse.Length - 2);
            }
            return RedirectToAction("All", "Advert");
        }

        [HttpGet]
        [Authorize(Roles = $"{AGENT},{ADMIN}")]
        public async Task<IActionResult> AllByAdvert(QueryDto model,string advertId)
        {
            if (model == null)
            {
                model = new QueryDto();
            }
            model.ItemsPerPage = 10;

            string url = $"api/application/all?advertId={advertId}";
            string json = JsonConvert.SerializeObject(model);
            HttpContent content = new StringContent(json, Encoding.UTF8, "application/json");

            //set JWT
            string tokenString = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

            HttpResponseMessage response = await httpClient.PostAsync(url, content);

            if (response.IsSuccessStatusCode)
            {
                string jsonContent = await response.Content.ReadAsStringAsync();
                QueryDtoResult<ApplicationDto> responseQueryDto = JsonConvert.DeserializeObject<QueryDtoResult<ApplicationDto>>(jsonContent, JsonSerializerSettingsProvider.GetCustomSettings())!;
                ResultQueryModel<ApplicationViewModel> applicationQueryModel = mapper.Map<ResultQueryModel<ApplicationViewModel>>(responseQueryDto);
                return View("All",applicationQueryModel);
            }
            else
            {
                return View("All",model);
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{AGENT},{ADMIN}")]
        public async Task<IActionResult> Accept(string id)
        {

            string url = $"api/application/accept?id={id}";

            //set JWT
            string tokenString = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

            HttpResponseMessage response = await httpClient.GetAsync(url);
            string message = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {
                TempData[SuccessMessage] = message;
            }
            else
            {
                TempData[WarningMessage] = message;
            }
            return RedirectToAction("All", "Advert");
        }

        [HttpGet]
        [Authorize(Roles = $"{AGENT},{ADMIN}")]
        public async Task<IActionResult> Decline(string id)
        {
            string url = $"api/application/decline?id={id}";

            //set JWT
            string tokenString = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

            HttpResponseMessage response = await httpClient.DeleteAsync(url);
            string message = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {
                TempData[SuccessMessage] = message;
            }
            else
            {
                TempData[WarningMessage] = message;
            }
            return RedirectToAction("All", "Advert");
        }
    }
}

HumanCapitalManagementSystem/HCMS.Web/Controllers/EmployeeController.cs
using AutoMapper;
using HCMS.Common;
using HCMS.Services.ServiceModels.BaseClasses;
using HCMS.Services.ServiceModels.Employee;
using HCMS.Web.ViewModels.BaseViewModel;
using HCMS.Web.ViewModels.Employee;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using static HCMS.Common.NotificationMessagesConstants;

namespace HCMS.Web.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly HttpClient httpClient;
        private readonly IMapper mapper;

        public EmployeeController(IHttpClientFactory httpClientFactory, IMapper mapper)
        {
            httpClient = httpClientFactory.CreateClient("WebApi");
            this.mapper = mapper;
        }

        [HttpGet]
        [Authorize(Roles = $"{RoleConstants.AGENT},{RoleConstants.ADMIN}")]
        public async Task<IActionResult> All(QueryDto model)
        {
            if (model == null)
            {
                model = new QueryDto();
            }

            string url = "api/employee/page";
            string json = JsonConvert.SerializeObject(model);
            HttpContent content = new StringContent(json, Encoding.UTF8, "application/json");

            //set JWT
            string tokenString = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

            HttpResponseMessage response = await httpClient.PostAsync(url, content);

            if (response.IsSuccessStatusCode)
            {
                string jsonContent = await response.Content.ReadAsStringAsync();
                QueryDtoResult<EmployeeDto> responseQueryDto = JsonConvert.DeserializeObject<QueryDtoResult<EmployeeDto>>(jsonContent, JsonSerializerSettingsProvider.GetCustomSettings())!;
                ResultQueryModel<EmployeeViewModel> employeeQueryModel = mapper.Map<ResultQueryModel<EmployeeViewModel>>(responseQueryDto);
                return View(employeeQueryModel);
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(string? redirect)
        {
            //check if it is redirect
            if (redirect != null)
            {
                TempData[WarningMessage] = redirect;
                return View(new EmployeeFormModel());
            }

            //get currently logged user ID
            Claim userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserId")!;
            string userId = userIdClaim.Value;

            //set the userIdGuid as query param
            string apiUrl = $"/api/employee/GetEmployeeDtoByUserId?userId={userId}";

            //set the JWT to the httpClient
            string JWT = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", JWT);

            // Make get request
            HttpResponseMessage response = await httpClient.GetAsync(apiUrl);


            if (response.IsSuccessStatusCode)
            {


                // Read the content as a JSON string
                string jsonContent = await response.Content.ReadAsStringAsync();

                // Deserialize the JSON into an EmployeeDto object

                //deserializing (if not working check the request from the other side) the JsonSerializerSettingsProvider is custom made in common
                EmployeeDto? employeeDto = JsonConvert.DeserializeObject<EmployeeDto>(jsonContent, JsonSerializerSettingsProvider.GetCustomSettings());

                //check if employee is not empty and attach it as a view model
                if (employeeDto != null)
                {
                    EmployeeFormModel model = mapper.Map<EmployeeFormModel>(employeeDto);
                    return View(model);
                }
            }
            return View(new EmployeeFormModel());
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(EmployeeFormModel model)
        {
            //validate input
            if (!ModelState.IsValid)
            {
                TempData[ErrorMessage] = "Please fulfill the requirements of the input fields!";
                return View(model);
            }
            //Validations completed
            Claim userIdClaim = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserId")!;

            EmployeeDto employeeDto = mapper.Map<EmployeeDto>(model);
            employeeDto.UserId = Guid.Parse(userIdClaim.Value);

            using (var form = new MultipartFormDataContent())
            {
                // Add the file content
                if (model.Photo != null)
                {
                    // Use a MemoryStream without disposing it here
                    var stream = new MemoryStream();
                    await model.Photo.CopyToAsync(stream);
                    stream.Position = 0;
                    form.Add(new StreamContent(stream), "file", model.Photo.FileName);
                }

                employeeDto.Photo = null;
                string jsonContent = JsonConvert.SerializeObject(employeeDto, JsonSerializerSettingsProvider.GetCustomSettings());
                form.Add(new StringContent(jsonContent, Encoding.UTF8, "application/json"), "employeeDto");

                string apiUrl = "/api/employee/UpdateEmployee";

                // Set JWT
                string tokenString = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
                this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", tokenString);

                HttpResponseMessage response = await httpClient.PostAsync(apiUrl, form);

                //if employee information successfully updated
                if (response.IsSuccessStatusCode)
                {
                    //if the principal has no employeeId claim -> add employee information for first time
                    if (!HttpContext.User.Claims.Any(c => c.Type == "EmployeeId"))
                    {
                        string userId = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "UserId")!.Value;

                        //JWT is already set
                        //set the employeeId to the claims of the user
                        string employeeApiUrl = $"/api/employee/EmployeeIdByUserId?UserId={userId}";
                        HttpResponseMessage employeeIdResponse = await httpClient.GetAsync(employeeApiUrl);
                        if (employeeIdResponse.IsSuccessStatusCode)
                        {
                            var userClaims = new List<Claim>(HttpContext.User.Claims);

                            // Add / update claims
                            string employeeId = await employeeIdResponse.Content.ReadAsStringAsync();
                            Claim employeeIdClaim = new Claim("EmployeeId", employeeId);
                            userClaims.RemoveAll(c => c.Type == "EmployeeId");
                            userClaims.Add(employeeIdClaim);

                            ClaimsIdentity updatedIdentity = new ClaimsIdentity(userClaims, HttpContext.User.Identity!.AuthenticationType, ClaimTypes.Name, ClaimTypes.Role);

                            ClaimsPrincipal updatedPrincipal = new ClaimsPrincipal(updatedIdentity);

                            await HttpContext.SignInAsync(updatedPrincipal);
                        }
                    }

                    TempData[SuccessMessage] = "You have successfully edited your personal information!";
                    return RedirectToAction("Home", "Home");
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                {
                    // Read the response content as a string
                    string responseContent = await response.Content.ReadAsStringAsync();
                    ModelState.AddModelError("GeneralError", responseContent);
                    return View(model);
                }
                else
                {
                    ModelState.AddModelError("GeneralError", "Unexpected error occurred!");
                    TempData[ErrorMessage] = "Unexpected error occurred!";
                    return View(model);
                }
            }
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Dismiss(string id)
        {
            //set the userIdGuid as query param
            string apiUrl = $"/api/employee/Dismiss?id={id}";

            //set the JWT to the httpClient
            string JWT = HttpContext.User.Claims.FirstOrDefault(c => c.Type == "JWT")!.Value;
            this.httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", JWT);

            // Make get request
            HttpResponseMessage response = await httpClient.GetAsync(apiUrl);


            if (response.IsSuccessStatusCode)
            {
                TempData[SuccessMessage] = "You have successfully left the company!";
                return RedirectToAction("Home", "Home");
            }
            else
            {
                TempData[ErrorMessage] = await response.Content.ReadAsStringAsync();
                return RedirectToAction("Company", "Select");
            }
        }


    }
}

HumanCapitalManagementSystem/HCMS.Web/Views/Home/HomeAgent.cshtml
<div class="container">
    <div class="row">
        <div class="col-8 height-50 carousel-background">
            <div id="carouselExampleCaptions" class="carousel slide carousel-fade mx-auto" data-bs-ride="carousel">
                <div class="container">
                    <div>
                        <div class="carousel-indicators">
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                        </div>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="https://pbs.twimg.com/media/EyjQfGYU8AEs0xE.jpg:large" class="mt-2 img-fluid background-image" alt="images">
                                <div class="carousel-caption d-none d-md-block">
                                    <p>Be What's Next</p>
                                </div>
                            </div>

                            <div class="carousel-item">
                                <img src="https://www.amd.com/system/files/2023-02/1890013-amd-twa-data-centers-1920x1080.jpg" class="mt-2 img-fluid background-image" alt="Image">
                                <div class="carousel-caption d-none d-md-block">
                                    <p>Advanced micro devices - processors and graphics technologies</p>
                                </div>
                            </div>

                            <div class="carousel-item">
                                <img src="https://www.intel.com/content/dam/www/public/us/en/newsroom/posts/intel-arc-logo-16x9.png" class="mt-2 img-fluid background-image" alt="images">
                                <div class="carousel-caption d-none d-md-block">
                                    <p>The new high-performance graphics brand</p>
                                </div>
                            </div>
                        </div>

                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="row">
                <div class="col-12 workrecords-background text-white height-25 d-flex flex-column align-items-center">
                    <!-- Content for the top right div -->
                    <div>
                        <h1 class="text-center text-bold tech-font">All Users</h1>
                        <p class="text-center mt-2">Information about the registered users, their roles and permissions</p>
                    </div>
                    <a asp-controller="User" asp-action="All" class="btn btn-outline-primary text-white border-white mt-auto mb-4">Go to users</a>
                </div>
            </div>
            <div class="row">
                <div class="col-12 recommendations-background text-white height-25 d-flex flex-column align-items-center">
                    <!-- Content for the bottom right div -->
                    <div>
                        <h1 class="text-center text-bold tech-font">Current workplace</h1>
                        <p class=" text-center mt-2">Add information about your current work place</p>
                    </div>
                    <a asp-controller="Company" asp-action="Select" class="btn btn-outline-primary text-white border-white mt-auto mb-4">Edit your workplace</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row height-25">
       
        <div class="col-4 employees-background text-white d-flex flex-column align-items-center">
            <div>
                <h1 class="text-center text-bold tech-font">Employees</h1>
                <p class="text-center mt-2">Discover a diverse and skilled workforce that's ready to make a difference. Explore their profiles, learn about their experiences, education and more</p>
            </div>
            <a asp-controller="Employee" asp-action="All" class="btn btn-outline-primary text-white border-white mt-auto mb-4">Go to employees</a>
        </div>

        <div class="col-4 companies-background text-white d-flex flex-column align-items-center">
            <div>
                <h1 class="text-center text-bold tech-font">My Company Employees</h1>
                <p class="text-center mt-2">Inspect and manage your current company employees</p>
            </div>
            <a asp-controller="Employee" asp-action="All" class="btn btn-outline-primary text-white border-white mt-auto mb-4">employees</a>
        </div>

        <div class="col-4 employees-background text-white d-flex flex-column align-items-center">
            <div>
                <h1 class="text-center text-bold tech-font">Companies</h1>
                <p class=" text-center mt-2">Explore a wide array of companies, each with a unique story and vision. Our platform showcases businesses from diverse sectors</p>
            </div>
            <a asp-controller="Company" asp-action="All" class="btn btn-outline-primary text-white border-white mt-auto mb-4">Go to companies</a>
        </div>

    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="~/css/homeAgent.css" asp-append-version="true" />
}

@* recommendations and endorsements provided by companies to our dedicated employees. Our platform showcases the trust and recognition that companies have for their team members. Explore a wide array of endorsements that highlight the skills, contributions, and expertise of employees. Gain insights into the strengths and achievements that companies value. Connect with employees who come highly recommended and bring a wealth of experience to your projects and endeavors. *@
@*  Our platform provides a comprehensive overview of their work records, highlighting their accomplishments, experiences, and contributions. *@

HumanCapitalManagementSystem/HCMS.Web/Views/Home/HomeEmployee.cshtml
<div class="container">
    <div class="row">
        <div class="col-8 height-50 carousel-background">
            <div id="carouselExampleCaptions" class="carousel slide carousel-fade mx-auto" data-bs-ride="carousel">
                <div class="container">
                    <div>
                        <div class="carousel-indicators">
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                        </div>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img src="https://pbs.twimg.com/media/EyjQfGYU8AEs0xE.jpg:large" class="mt-2 img-fluid background-image" alt="images">
                                <div class="carousel-caption d-none d-md-block">
                                    <p>Be What's Next</p>
                                </div>
                            </div>

                            <div class="carousel-item">
                                <img src="https://visualstudio.microsoft.com/wp-content/uploads/2023/01/VisualStudioLogo.webp" class="mt-2 img-fluid background-image" alt="Image">
                                <div class="carousel-caption d-none d-md-block">
                                    <p>Advanced micro devices - processors and graphics technologies</p>
                                </div>
                            </div>

                            <div class="carousel-item">
                                <img src="https://www.intel.com/content/dam/www/public/us/en/newsroom/posts/intel-arc-logo-16x9.png" class="mt-2 img-fluid background-image" alt="images">
                                <div class="carousel-caption d-none d-md-block">
                                    <p>The new high-performance graphics brand</p>
                                </div>
                            </div>
                        </div>

                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        @* CAROUSEL END *@

        <div class="col-4">
            <div class="row">
                <div class="col-12 workrecords-background text-white height-25 d-flex flex-column align-items-center">
                    <!-- Content for the top right div -->
                    <div>
                        <h1 class="text-center text-bold tech-font">My Work Records</h1>
                        <p class="text-center mt-2">Search, edit and delete your saved personal work records, or add new one</p>
                    </div>
                    <a asp-controller="WorkRecord" asp-action="Add" class="btn btn-outline-primary text-white border-white mt-auto mb-4">Add records</a>
                </div>
            </div>
            <div class="row">
                <div class="col-12 recommendations-background text-white height-25 d-flex flex-column align-items-center">
                    <!-- Content for the bottom right div -->
                    <div>
                        <h1 class="text-center text-bold tech-font">Edit Educations</h1>
                        <p class="text-center mt-2">Edit, add and delete detailed information about your educations and diplomas.</p>
                    </div>
                    <a asp-controller="Education" asp-action="Edit" class="btn btn-outline-primary text-white border-white mt-auto mb-4">Add Education</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row height-25">
        <div class="col-4 employees-background text-white d-flex flex-column align-items-center">
            <div>
                <h1 class="text-center text-bold tech-font">Find a job</h1>
                <p class="text-center mt-2">Discover a diverse and skilled workforce that's ready to make a difference. Explore their profiles, learn about their experiences, education and more</p>
            </div>
            <a asp-controller="Application" asp-action="Apply" class="btn btn-outline-primary text-white border-white mt-auto mb-4">Apply for job</a>
        </div>

        <div class="col-4 companies-background text-white d-flex flex-column align-items-center">
            <div>
                <h1 class="text-center text-bold tech-font">Edit personal information</h1>
                <p class=" text-center mt-2">Edit or edit your personal public information</p>
            </div>
            <a asp-controller="Employee" asp-action="Edit" class="btn btn-outline-primary text-white border-white mt-auto mb-4">Personal info</a>
        </div>

        <div class="col-4 applications-background text-white d-flex flex-column align-items-center">
            <div>
                <h1 class="text-center text-bold tech-font">User profile</h1>
                <p class=" text-center mt-2">Review and edit your login credentials</p>
            </div>
            <a asp-controller="User" asp-action="Profile" asp-route-id="@User.Claims.FirstOrDefault(c => c.Type == "UserId")!.Value" class="btn btn-outline-primary text-white border-white mt-auto mb-4">Edit your workplace</a>
        </div>
    </div>
</div>

@section Styles {
    <link rel="stylesheet" href="~/css/homeAgent.css" asp-append-version="true" />
}

HumanCapitalManagementSystem/HCMS.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "- Home";
}

<div class="text-center">
    <h1 class="text-white fw-bold display-4">Welcome to Human Capital Recourse System!</h1>
</div>